name: manubergman
favicon: null
layout_spectrum: 0.50188
typography_spectrum: 0.2851889750454575
title: Manu Bergman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#1f2d2e'
    - '#524630'
    - '#4e666a'
    - '#c3bda3'
  brandStrength: 0.9655872227158397
  lightness: 0.41682530264370143
  saturation: 0.6085161531809717
  rhythmicContrast: 0.75
purpose: []
